# Site settings
title: Stanford CoCoLab
email: erindb@stanford.edu
description: >
  Stanford Computation and Cognition Lab
  (affectionately called CoCoLab)
#baseurl: "/home/feste/everything-cocolab/WWW"
#url: "https://web.stanford.edu/~erindb/cocowebsite/WWW"
#url: "file://" # the base hostname & protocol for your site
#url: "http://cocolab.stanford.edu/"
github_username:  StanfordCoCoLab

gems: ['jekyll/scholar']

max_year: 2015 #the most recent year with papers published
# i should figure out how to automate that...

# Build settings
markdown: redcarpet

# for BibTeX
scholar:
  style: apa
  locale: en

  sort_by: year
  order: descending

  bibliography_list_tag: ul

  source: ./_bibliography
  bibliography: cocolab
  bibliography_template: <p>{{reference}} {{entry.annote}}</p>

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   "[Abstract/BibTeX]"

  query: "@*"

exclude:
  - "files"
  - "wikiuploads"

keep_files:
  - "files"
  - "wikiuploads"
